-- Inbound DLQ (Dead Letter Queue) для Integration Broker.
--
-- Назначение:
--  1) сохранять входящие сообщения, которые не удалось обработать;
--  2) обеспечивать эксплуатационную диагностику (что упало, почему, сколько раз);
--  3) поддерживать ручной/админский replay без потери исходного payload.
--
-- Важно:
--  * санитизация заголовков выполняется на уровне приложения (не храним токены/секреты);
--  * решение LOCKED по идемпотентности не является poison message и не попадает в DLQ.

CREATE TABLE IF NOT EXISTS ib_inbound_dlq (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status             VARCHAR(32) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,

    kind               VARCHAR(16) NOT NULL,
    type               VARCHAR(128) NOT NULL,

    message_id         VARCHAR(128) NULL,
    correlation_id     VARCHAR(128) NULL,
    branch_id          VARCHAR(128) NULL,
    user_id            VARCHAR(128) NULL,

    headers_json       TEXT NULL,
    payload_json       TEXT NULL,
    source_meta_json   TEXT NULL,

    idem_key           VARCHAR(128) NULL,

    attempts           INT NOT NULL DEFAULT 0,
    max_attempts       INT NOT NULL DEFAULT 10,
    last_error_at      TIMESTAMP WITH TIME ZONE NULL,
    error_code         VARCHAR(64) NULL,
    error_message      TEXT NULL,

    replayed_at        TIMESTAMP WITH TIME ZONE NULL,
    replay_result_json TEXT NULL
);

CREATE INDEX IF NOT EXISTS ix_ib_inbound_dlq_status_updated
    ON ib_inbound_dlq (status, updated_at DESC);

CREATE INDEX IF NOT EXISTS ix_ib_inbound_dlq_message_id
    ON ib_inbound_dlq (message_id);
