-- Outbox (messaging + REST) для Integration Broker.
--
-- Цели:
--  1) обеспечить надёжную доставку ("exactly-once-like" на уровне интеграции);
--  2) позволить ретраи с backoff без потери данных;
--  3) дать оператору инструменты для replay/диагностики.
--
-- Примечание по статусам:
--  PENDING  - ожидает отправки
--  SENDING  - выбран диспетчером и отправляется (защита от конкуренции)
--  SENT     - отправлен успешно
--  DEAD     - исчерпаны попытки (ручной разбор)

CREATE TABLE IF NOT EXISTS ib_messaging_outbox (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    status             VARCHAR(16) NOT NULL,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,

    provider           VARCHAR(64)  NOT NULL,
    destination        TEXT         NOT NULL,
    message_key        TEXT         NULL,

    headers_json       TEXT         NULL,
    payload_json       TEXT         NOT NULL,

    source_message_id  VARCHAR(128) NULL,
    correlation_id     VARCHAR(128) NULL,
    idem_key           VARCHAR(128) NULL,

    attempts           INT NOT NULL DEFAULT 0,
    max_attempts       INT NOT NULL DEFAULT 10,
    next_attempt_at    TIMESTAMP WITH TIME ZONE NOT NULL,

    last_error_at      TIMESTAMP WITH TIME ZONE NULL,
    last_error_code    VARCHAR(64) NULL,
    last_error_message TEXT NULL
);

CREATE INDEX IF NOT EXISTS ix_ib_messaging_outbox_status_next
    ON ib_messaging_outbox (status, next_attempt_at);

CREATE INDEX IF NOT EXISTS ix_ib_messaging_outbox_updated
    ON ib_messaging_outbox (updated_at DESC);


CREATE TABLE IF NOT EXISTS ib_rest_outbox (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    status                VARCHAR(16) NOT NULL,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,

    http_method           VARCHAR(16) NOT NULL,
    url                   TEXT        NOT NULL,

    headers_json          TEXT        NULL,
    body_json             TEXT        NULL,

    idempotency_key       VARCHAR(128) NULL,

    source_message_id     VARCHAR(128) NULL,
    correlation_id        VARCHAR(128) NULL,
    idem_key              VARCHAR(128) NULL,

    attempts              INT NOT NULL DEFAULT 0,
    max_attempts          INT NOT NULL DEFAULT 10,
    next_attempt_at       TIMESTAMP WITH TIME ZONE NOT NULL,

    treat_4xx_as_success  TEXT NULL,

    last_error_at         TIMESTAMP WITH TIME ZONE NULL,
    last_error_code       VARCHAR(64) NULL,
    last_error_message    TEXT NULL,

    last_http_status      INT NULL
);

CREATE INDEX IF NOT EXISTS ix_ib_rest_outbox_status_next
    ON ib_rest_outbox (status, next_attempt_at);

CREATE INDEX IF NOT EXISTS ix_ib_rest_outbox_updated
    ON ib_rest_outbox (updated_at DESC);
