package ru.aritmos.integrationbroker.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import ru.aritmos.integrationbroker.model.InboundEnvelope;

import java.sql.Connection;
import java.sql.Statement;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class InboundDlqServiceAdminOpsTest {

    @Test
    void previewAndMarkIgnoredBatch_shouldWork() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:dlq_admin_ops;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_inbound_dlq (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        kind VARCHAR(32) NOT NULL,
                        type VARCHAR(128) NOT NULL,
                        message_id VARCHAR(128),
                        correlation_id VARCHAR(128),
                        branch_id VARCHAR(128),
                        user_id VARCHAR(128),
                        headers_json TEXT,
                        payload_json TEXT,
                        source_meta_json TEXT,
                        idem_key VARCHAR(128),
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        last_error_at TIMESTAMP WITH TIME ZONE,
                        error_code VARCHAR(64),
                        error_message TEXT,
                        replayed_at TIMESTAMP WITH TIME ZONE,
                        replay_result_json TEXT
                    )
                    """);
        }

        ObjectMapper om = new ObjectMapper();
        InboundDlqService service = new InboundDlqService(ds, om);

        InboundEnvelope env = new InboundEnvelope(
                InboundEnvelope.Kind.EVENT,
                "visit.created",
                om.readTree("{\"auth\":\"Bearer secret-token\"}"),
                Map.of("Authorization", "Bearer top-secret"),
                "m1",
                "c1",
                "B1",
                "u1",
                Map.of("source", "crm")
        );

        long id = service.put(env, "k1", "E1", "failed", 5, true);
        assertTrue(id > 0);

        String preview = service.sanitizedPayloadPreview(id, 200);
        assertNotNull(preview);
        assertTrue(preview.contains("Bearer ***"));

        int updated = service.markIgnoredBatch("PENDING", "visit.created", "crm", "B1", 10, "ignore by operator");
        assertEquals(1, updated);

        InboundDlqService.DlqRecord rec = service.get(id);
        assertEquals("DEAD", rec.status());
        assertEquals("IGNORED_BY_ADMIN", rec.errorCode());

        assertEquals(1, service.list("DEAD", "visit.created", "crm", "B1", "operator", 10).size());
        int requeued = service.requeueIgnoredBatch("visit.created", "crm", "B1", "operator", 10, "retry after fix");
        assertEquals(1, requeued);
        InboundDlqService.DlqRecord requeuedRec = service.get(id);
        assertEquals("PENDING", requeuedRec.status());
        assertEquals("REQUEUED_BY_ADMIN", requeuedRec.errorCode());
    }

    @Test
    void autoIgnoreKnownNonRetriable_shouldMovePendingToDead() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:dlq_auto_ignore;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_inbound_dlq (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        kind VARCHAR(32) NOT NULL,
                        type VARCHAR(128) NOT NULL,
                        message_id VARCHAR(128),
                        correlation_id VARCHAR(128),
                        branch_id VARCHAR(128),
                        user_id VARCHAR(128),
                        headers_json TEXT,
                        payload_json TEXT,
                        source_meta_json TEXT,
                        idem_key VARCHAR(128),
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        last_error_at TIMESTAMP WITH TIME ZONE,
                        error_code VARCHAR(64),
                        error_message TEXT,
                        replayed_at TIMESTAMP WITH TIME ZONE,
                        replay_result_json TEXT
                    )
                    """);
        }
        ObjectMapper om = new ObjectMapper();
        InboundDlqService service = new InboundDlqService(ds, om);
        InboundEnvelope env = new InboundEnvelope(InboundEnvelope.Kind.EVENT, "visit", om.readTree("{}"), Map.of(), "m", "c", null, null, Map.of("source", "crm"));
        long id = service.put(env, "k", "VALIDATION_ERROR", "invalid payload", 5, true);
        int changed = service.autoIgnoreKnownNonRetriable(10, "policy auto-ignore");
        assertEquals(1, changed);
        assertEquals("DEAD", service.get(id).status());
        assertEquals("IGNORED_AUTO_NON_RETRIABLE", service.get(id).errorCode());
    }

    @Test
    void list_shouldSupportCorrelationFilterAndTrimInput() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:dlq_corr_filter;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_inbound_dlq (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        kind VARCHAR(32) NOT NULL,
                        type VARCHAR(128) NOT NULL,
                        message_id VARCHAR(128),
                        correlation_id VARCHAR(128),
                        branch_id VARCHAR(128),
                        user_id VARCHAR(128),
                        headers_json TEXT,
                        payload_json TEXT,
                        source_meta_json TEXT,
                        idem_key VARCHAR(128),
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        last_error_at TIMESTAMP WITH TIME ZONE,
                        error_code VARCHAR(64),
                        error_message TEXT,
                        replayed_at TIMESTAMP WITH TIME ZONE,
                        replay_result_json TEXT
                    )
                    """);
        }
        ObjectMapper om = new ObjectMapper();
        InboundDlqService service = new InboundDlqService(ds, om);

        InboundEnvelope c1 = new InboundEnvelope(InboundEnvelope.Kind.EVENT, "visit", om.readTree("{}"), Map.of(), "m1", "corr-1", "B1", "u1", Map.of("source", "crm"));
        InboundEnvelope c2 = new InboundEnvelope(InboundEnvelope.Kind.EVENT, "visit", om.readTree("{}"), Map.of(), "m2", "corr-2", "B1", "u1", Map.of("source", "crm"));
        service.put(c1, "k1", "E", "msg", 3, true);
        service.put(c2, "k2", "E", "msg", 3, true);

        assertEquals(1, service.list(" PENDING ", " visit ", " crm ", " B1 ", null, " corr-1 ", 10).size());
        assertEquals("corr-1", service.list("PENDING", "visit", "crm", "B1", null, "corr-1", 10).get(0).correlationId());
    }

}
