package ru.aritmos.integrationbroker.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import ru.aritmos.integrationbroker.model.InboundEnvelope;

import java.sql.Connection;
import java.sql.Statement;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

class InboundDlqServiceAdminOpsTest {

    @Test
    void previewAndMarkIgnoredBatch_shouldWork() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:dlq_admin_ops;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");
        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_inbound_dlq (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        kind VARCHAR(32) NOT NULL,
                        type VARCHAR(128) NOT NULL,
                        message_id VARCHAR(128),
                        correlation_id VARCHAR(128),
                        branch_id VARCHAR(128),
                        user_id VARCHAR(128),
                        headers_json TEXT,
                        payload_json TEXT,
                        source_meta_json TEXT,
                        idem_key VARCHAR(128),
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        last_error_at TIMESTAMP WITH TIME ZONE,
                        error_code VARCHAR(64),
                        error_message TEXT,
                        replayed_at TIMESTAMP WITH TIME ZONE,
                        replay_result_json TEXT
                    )
                    """);
        }

        ObjectMapper om = new ObjectMapper();
        InboundDlqService service = new InboundDlqService(ds, om);

        InboundEnvelope env = new InboundEnvelope(
                InboundEnvelope.Kind.EVENT,
                "visit.created",
                om.readTree("{\"auth\":\"Bearer secret-token\"}"),
                Map.of("Authorization", "Bearer top-secret"),
                "m1",
                "c1",
                "B1",
                "u1",
                Map.of("source", "crm")
        );

        long id = service.put(env, "k1", "E1", "failed", 5, true);
        assertTrue(id > 0);

        String preview = service.sanitizedPayloadPreview(id, 200);
        assertNotNull(preview);
        assertTrue(preview.contains("Bearer ***"));

        int updated = service.markIgnoredBatch("PENDING", "visit.created", "crm", "B1", 10, "ignore by operator");
        assertEquals(1, updated);

        InboundDlqService.DlqRecord rec = service.get(id);
        assertEquals("DEAD", rec.status());
        assertEquals("IGNORED_BY_ADMIN", rec.errorCode());
    }
}
