package ru.aritmos.integrationbroker.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessagingOutboxServiceReplayByCorrelationTest {

    @Test
    void replayByCorrelation_shouldSupportDryRunAndReplay() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:msg_outbox_corr;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_messaging_outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        provider VARCHAR(80) NOT NULL,
                        destination VARCHAR(200) NOT NULL,
                        message_key VARCHAR(120) NULL,
                        headers_json TEXT NULL,
                        payload_json TEXT NULL,
                        source_message_id VARCHAR(128) NULL,
                        correlation_id VARCHAR(128) NULL,
                        idem_key VARCHAR(128) NULL,
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        last_error_at TIMESTAMP WITH TIME ZONE NULL,
                        last_error_code VARCHAR(64) NULL,
                        last_error_message TEXT NULL
                    )
                    """);
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('DEAD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d','cid-1',3,5,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('SENT',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d','cid-1',1,5,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('SENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d','cid-1',2,5,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('DEAD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d','cid-2',2,5,CURRENT_TIMESTAMP)");
        }

        MessagingOutboxService service = new MessagingOutboxService(ds, new ObjectMapper(), null, new OutboundDryRunState(false, null));
        int dryRunCandidates = service.replayByCorrelation("cid-1", 10, true, true);
        assertEquals(2, dryRunCandidates);

        int replayed = service.replayByCorrelation("cid-1", 10, true, false);
        assertEquals(2, replayed);

        assertEquals(2, service.list("PENDING", 20).stream().filter(i -> "d".equals(i.destination())).count());
    }

    @Test
    void replayByCorrelation_shouldSupportSuppressPublishMode() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:msg_outbox_corr_suppress;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_messaging_outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        provider VARCHAR(80) NOT NULL,
                        destination VARCHAR(200) NOT NULL,
                        message_key VARCHAR(120) NULL,
                        headers_json TEXT NULL,
                        payload_json TEXT NULL,
                        source_message_id VARCHAR(128) NULL,
                        correlation_id VARCHAR(128) NULL,
                        idem_key VARCHAR(128) NULL,
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        last_error_at TIMESTAMP WITH TIME ZONE NULL,
                        last_error_code VARCHAR(64) NULL,
                        last_error_message TEXT NULL
                    )
                    """);
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('DEAD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d','cid-sup',3,5,CURRENT_TIMESTAMP)");
        }

        MessagingOutboxService service = new MessagingOutboxService(ds, new ObjectMapper(), null, new OutboundDryRunState(false, null));
        int affected = service.replayByCorrelation("cid-sup", 10, false, false, true, "operator suppress");
        assertEquals(1, affected);
        assertEquals(1, service.list("SENT", 10).size());
    }

    @Test
    void list_shouldSupportCombinedStatusAndCorrelationFilters() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:msg_outbox_list_filters;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_messaging_outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        provider VARCHAR(80) NOT NULL,
                        destination VARCHAR(200) NOT NULL,
                        message_key VARCHAR(120) NULL,
                        headers_json TEXT NULL,
                        payload_json TEXT NULL,
                        source_message_id VARCHAR(128) NULL,
                        correlation_id VARCHAR(128) NULL,
                        idem_key VARCHAR(128) NULL,
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        last_error_at TIMESTAMP WITH TIME ZONE NULL,
                        last_error_code VARCHAR(64) NULL,
                        last_error_message TEXT NULL
                    )
                    """);
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d1','cid-x',0,5,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('DEAD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d2','cid-x',0,5,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_messaging_outbox(status,created_at,updated_at,provider,destination,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'p','d3','cid-y',0,5,CURRENT_TIMESTAMP)");
        }

        MessagingOutboxService service = new MessagingOutboxService(ds, new ObjectMapper(), null, new OutboundDryRunState(false, null));
        assertEquals(1, service.list(" PENDING ", " cid-x ", 10).size());
        assertEquals(2, service.list(null, "cid-x", 10).size());
    }

}
