package ru.aritmos.integrationbroker.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;

import static org.junit.jupiter.api.Assertions.*;

class RestOutboxServicePriorityAndFingerprintTest {

    @Test
    void priorityBumpAndFingerprint_shouldWork() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:rest_outbox_priority;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_rest_outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        http_method VARCHAR(16) NOT NULL,
                        url TEXT NOT NULL,
                        connector_id VARCHAR(100),
                        path VARCHAR(2000),
                        headers_json TEXT NULL,
                        body_json TEXT NULL,
                        idempotency_key VARCHAR(128) NULL,
                        source_message_id VARCHAR(128) NULL,
                        correlation_id VARCHAR(128) NULL,
                        idem_key VARCHAR(128) NULL,
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        treat_4xx_as_success TEXT NULL,
                        last_error_at TIMESTAMP WITH TIME ZONE NULL,
                        last_error_code VARCHAR(64) NULL,
                        last_error_message TEXT NULL,
                        last_http_status INT NULL
                    )
                    """);
            st.execute("INSERT INTO ib_rest_outbox(status,created_at,updated_at,http_method,url,connector_id,path,body_json,idempotency_key,idem_key,attempts,max_attempts,next_attempt_at) VALUES ('DEAD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'POST','http://a','c1','/x','{\"a\":1}','idem-header','idem-key',2,3,CURRENT_TIMESTAMP)");
        }

        RestOutboxService service = new RestOutboxService(ds, new ObjectMapper(), null, null);
        assertTrue(service.priorityBump(1L, 120));

        RestOutboxService.RestRecord rec = service.get(1L);
        assertNotNull(rec);
        assertEquals("PENDING", rec.status());

        RestOutboxService.DedupFingerprintPreview preview = service.dedupFingerprintPreview(1L);
        assertNotNull(preview);
        assertEquals(1L, preview.id());
        assertNotNull(preview.fingerprint());
        assertEquals(64, preview.fingerprint().length());
        assertTrue(preview.materialLength() > 0);
    }
}
