package ru.aritmos.integrationbroker.core;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;

import java.sql.Connection;
import java.sql.Statement;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;

class RestOutboxServiceListFilterTest {

    @Test
    void list_shouldFilterByConnectorId() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:rest_outbox_filter;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_rest_outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        http_method VARCHAR(16) NOT NULL,
                        url TEXT NOT NULL,
                        connector_id VARCHAR(100),
                        path VARCHAR(2000),
                        headers_json TEXT NULL,
                        body_json TEXT NULL,
                        idempotency_key VARCHAR(128) NULL,
                        source_message_id VARCHAR(128) NULL,
                        correlation_id VARCHAR(128) NULL,
                        idem_key VARCHAR(128) NULL,
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        treat_4xx_as_success TEXT NULL,
                        last_error_at TIMESTAMP WITH TIME ZONE NULL,
                        last_error_code VARCHAR(64) NULL,
                        last_error_message TEXT NULL,
                        last_http_status INT NULL
                    )
                    """);
            st.execute("INSERT INTO ib_rest_outbox(status,created_at,updated_at,http_method,url,connector_id,path,attempts,max_attempts,next_attempt_at) VALUES ('PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'POST','http://a','c1','/a',0,3,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_rest_outbox(status,created_at,updated_at,http_method,url,connector_id,path,attempts,max_attempts,next_attempt_at) VALUES ('PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'POST','http://b','c2','/b',0,3,CURRENT_TIMESTAMP)");
        }

        RestOutboxService service = new RestOutboxService(ds, new ObjectMapper(), null, null);
        List<RestOutboxService.RestListItem> c1 = service.list("PENDING", "c1", 50);
        List<RestOutboxService.RestListItem> all = service.list("PENDING", null, 50);

        assertEquals(1, c1.size());
        assertEquals("c1", c1.get(0).connectorId());
        assertEquals(2, all.size());
    }
    @Test
    void list_shouldSupportCorrelationAndCombinedFilters() throws Exception {
        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:rest_outbox_corr_filter;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        ds.setPassword("");

        try (Connection c = ds.getConnection(); Statement st = c.createStatement()) {
            st.execute("""
                    CREATE TABLE IF NOT EXISTS ib_rest_outbox (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(16) NOT NULL,
                        created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        http_method VARCHAR(16) NOT NULL,
                        url TEXT NOT NULL,
                        connector_id VARCHAR(100),
                        path VARCHAR(2000),
                        headers_json TEXT NULL,
                        body_json TEXT NULL,
                        idempotency_key VARCHAR(128) NULL,
                        source_message_id VARCHAR(128) NULL,
                        correlation_id VARCHAR(128) NULL,
                        idem_key VARCHAR(128) NULL,
                        attempts INT NOT NULL DEFAULT 0,
                        max_attempts INT NOT NULL DEFAULT 10,
                        next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL,
                        treat_4xx_as_success TEXT NULL,
                        last_error_at TIMESTAMP WITH TIME ZONE NULL,
                        last_error_code VARCHAR(64) NULL,
                        last_error_message TEXT NULL,
                        last_http_status INT NULL
                    )
                    """);
            st.execute("INSERT INTO ib_rest_outbox(status,created_at,updated_at,http_method,url,connector_id,path,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'POST','http://a','c1','/a','cid-a',0,3,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_rest_outbox(status,created_at,updated_at,http_method,url,connector_id,path,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('DEAD',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'POST','http://b','c1','/b','cid-a',0,3,CURRENT_TIMESTAMP)");
            st.execute("INSERT INTO ib_rest_outbox(status,created_at,updated_at,http_method,url,connector_id,path,correlation_id,attempts,max_attempts,next_attempt_at) VALUES ('PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'POST','http://c','c2','/c','cid-b',0,3,CURRENT_TIMESTAMP)");
        }

        RestOutboxService service = new RestOutboxService(ds, new ObjectMapper(), null, null);
        assertEquals(1, service.list(" PENDING ", " c1 ", " cid-a ", 20).size());
        assertEquals(2, service.listByCorrelation(" cid-a ", 20).size());
    }

}
